service: katana

frameworkVersion: '2'

provider:
  name: aws
  region: us-east-1
  stage: dev
  runtime: python3.7
  timeout: 30
  apiGateway:
    binaryMediaTypes:
      - '*/*'

package:
  include:
    - handler.py
    - deps/**
  exclude:
    - .git/**

functions:
  image-cropter:
    handler: handler.cropter
    memorySize: 512
    events:
      - http:
          path: image/cropter
          method: post
